"""beschrijving van wijziging

Revision ID: 0b11b56bcbeb
Revises: e1a29c685536
Create Date: 2025-08-14 08:10:19.219138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b11b56bcbeb'
down_revision = 'e1a29c685536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_postcard_buyer_id', 'user', ['buyer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_poster_buyer_id', 'user', ['buyer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.drop_constraint('fk_poster_buyer_id', type_='foreignkey')
        batch_op.drop_column('buyer_id')

    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.drop_constraint('fk_postcard_buyer_id', type_='foreignkey')
        batch_op.drop_column('buyer_id')

    # ### end Alembic commands ###
