"""Add Postcard model

Revision ID: 0ba7883ada77
Revises: a9cef2187349
Create Date: 2025-08-06 10:06:14.138954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba7883ada77'
down_revision = 'a9cef2187349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('front_image_url', sa.String(length=255), nullable=True),
    sa.Column('back_image_url', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_auction', sa.Boolean(), nullable=True),
    sa.Column('auction_min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('auction_end', sa.DateTime(), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postcard')
    # ### end Alembic commands ###
