"""Verzendgegevens toegevoegd aan User

Revision ID: 12cffd82f0f9
Revises: bd3f6d813ebf
Create Date: 2025-07-18 11:08:50.974137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cffd82f0f9'
down_revision = 'bd3f6d813ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_shipping', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('pickup_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('platform_payment_only', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('platform_payment_only')
        batch_op.drop_column('pickup_only')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('allow_shipping')

    # ### end Alembic commands ###
