"""Add CartItem model

Revision ID: 3bd537eeaa7b
Revises: daef48153eef
Create Date: 2025-08-10 18:54:53.763751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd537eeaa7b'
down_revision = 'daef48153eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_postcard_buyer_id'), type_='foreignkey')
        batch_op.drop_column('buyer_id')

    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_poster_buyer_id'), type_='foreignkey')
        batch_op.drop_column('buyer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_poster_buyer_id'), 'user', ['buyer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_postcard_buyer_id'), 'user', ['buyer_id'], ['id'], ondelete='SET NULL')

    op.drop_table('cart_item')
    # ### end Alembic commands ###
