"""Add Art model

Revision ID: 45248e188e1a
Revises: a82e303ad7b9
Create Date: 2025-09-11 14:35:11.702667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45248e188e1a'
down_revision = 'a82e303ad7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('art',
    sa.Column('allow_shipping', sa.Boolean(), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pickup_only', sa.Boolean(), nullable=True),
    sa.Column('platform_payment_only', sa.Boolean(), nullable=True),
    sa.Column('cash_payment_only', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_auction', sa.Boolean(), nullable=True),
    sa.Column('auction_min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('auction_end', sa.DateTime(), nullable=True),
    sa.Column('artist', sa.String(length=140), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rek_id', sa.Integer(), nullable=True),
    sa.Column('verdieping_id', sa.Integer(), nullable=True),
    sa.Column('positie', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['rek_id'], ['rek.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['verdieping_id'], ['rek_verdieping.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('art')
    # ### end Alembic commands ###
