"""Add publisher column to postcard

Revision ID: 5111c9bb536c
Revises: 0ba7883ada77
Create Date: 2025-08-06 10:42:14.501472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5111c9bb536c'
down_revision = '0ba7883ada77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.drop_column('publisher')

    # ### end Alembic commands ###
