"""add appointment_slot table

Revision ID: 575481ac057d
Revises: e14e17bd6c31
Create Date: 2025-09-04 14:19:11.291473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575481ac057d'
down_revision = 'e14e17bd6c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('reserved_by_id', sa.Integer(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['reserved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_slot')
    # ### end Alembic commands ###
