"""Voeg cash payment toe

Revision ID: 7d2d8913e3e4
Revises: 12cffd82f0f9
Create Date: 2025-07-18 12:16:13.861973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2d8913e3e4'
down_revision = '12cffd82f0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_payment_only', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cash_payment_only')

    # ### end Alembic commands ###
