"""Add is_admin field to User model

Revision ID: 897a8ddd6c65
Revises: 7d2d8913e3e4
Create Date: 2025-08-04 11:23:51.640360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897a8ddd6c65'
down_revision = '7d2d8913e3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False,server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
