"""Add about_shop field to User model

Revision ID: 996c18420de0
Revises: 575481ac057d
Create Date: 2025-09-10 11:51:46.448641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996c18420de0'
down_revision = '575481ac057d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_shop', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_shop')

    # ### end Alembic commands ###
