"""Add hero section fields to User

Revision ID: a82e303ad7b9
Revises: d3899dda7e70
Create Date: 2025-09-11 11:44:29.053905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82e303ad7b9'
down_revision = 'd3899dda7e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_section_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hero_section_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hero_section_image')
        batch_op.drop_column('hero_section_enabled')

    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
