"""rek en rekverdieping toegevoegd

Revision ID: d1b687575aa8
Revises: d4053f1acb81
Create Date: 2025-09-04 09:41:33.418323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b687575aa8'
down_revision = 'd4053f1acb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rek_verdieping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rek_id', sa.Integer(), nullable=False),
    sa.Column('nummer', sa.Integer(), nullable=False),
    sa.Column('links', sa.String(length=1), nullable=True),
    sa.Column('midden', sa.String(length=1), nullable=True),
    sa.Column('rechts', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['rek_id'], ['rek.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rek_verdieping')
    op.drop_table('rek')
    # ### end Alembic commands ###
