"""Add account_type, pro_tier, vat_number to User and buyer_id to items

Revision ID: d4053f1acb81
Revises: 0b11b56bcbeb
Create Date: 2025-08-14 14:32:33.234072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4053f1acb81'
down_revision = '0b11b56bcbeb'
branch_labels = None
depends_on = None


def upgrade():
   
   
    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_postcard_buyer_id'), type_='foreignkey')
        batch_op.drop_column('buyer_id')

    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_poster_buyer_id'), type_='foreignkey')
        batch_op.drop_column('buyer_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(length=10), nullable=False, server_default='basic'))
        batch_op.add_column(sa.Column('pro_tier', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('vat_number', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('vat_number')
        batch_op.drop_column('pro_tier')
        batch_op.drop_column('account_type')

    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_poster_buyer_id'), 'user', ['buyer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_postcard_buyer_id'), 'user', ['buyer_id'], ['id'], ondelete='SET NULL')

    op.create_table('_alembic_tmp_book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('author', sa.VARCHAR(length=150), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('author_description', sa.TEXT(), nullable=True),
    sa.Column('genre', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('is_auction', sa.BOOLEAN(), nullable=True),
    sa.Column('auction_min_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('auction_end', sa.DATETIME(), nullable=True),
    sa.Column('sold_count', sa.INTEGER(), nullable=True),
    sa.Column('sold', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), nullable=True),
    sa.Column('front_image', sa.VARCHAR(length=150), nullable=True),
    sa.Column('side_image', sa.VARCHAR(length=150), nullable=True),
    sa.Column('back_image', sa.VARCHAR(length=150), nullable=True),
    sa.Column('view_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], name=op.f('fk_book_buyer_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_book_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
