"""Add rek_id, verdieping_id, positie to book/postcard/poster

Revision ID: e14e17bd6c31
Revises: ead4737031de
Create Date: 2025-09-04 13:05:18.966714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14e17bd6c31'
down_revision = 'ead4737031de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rek_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verdieping_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('positie', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key('fk_book_verdieping_id', 'rek_verdieping', ['verdieping_id'], ['id'])
        batch_op.create_foreign_key('fk_book_rek_id', 'rek', ['rek_id'], ['id'])

    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rek_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verdieping_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('positie', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key('fk_postcard_rek_id', 'rek', ['rek_id'], ['id'])
        batch_op.create_foreign_key('fk_postcard_verdieping_id', 'rek_verdieping', ['verdieping_id'], ['id'])

    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rek_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verdieping_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('positie', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key('fk_poster_rek_id', 'rek', ['rek_id'], ['id'])
        batch_op.create_foreign_key('fk_poster_verdieping_id', 'rek_verdieping', ['verdieping_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('positie')
        batch_op.drop_column('verdieping_id')
        batch_op.drop_column('rek_id')

    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('positie')
        batch_op.drop_column('verdieping_id')
        batch_op.drop_column('rek_id')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('positie')
        batch_op.drop_column('verdieping_id')
        batch_op.drop_column('rek_id')

    # ### end Alembic commands ###
