"""Update payment and shipping fields

Revision ID: e1a29c685536
Revises: 77bf280faece
Create Date: 2025-08-12 10:21:04.717466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a29c685536'
down_revision = '77bf280faece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_shipping', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('pickup_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('platform_payment_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cash_payment_only', sa.Boolean(), nullable=True))

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_shipping', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('pickup_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('platform_payment_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cash_payment_only', sa.Boolean(), nullable=True))

    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_shipping', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('pickup_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('platform_payment_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cash_payment_only', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.drop_column('cash_payment_only')
        batch_op.drop_column('platform_payment_only')
        batch_op.drop_column('pickup_only')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('allow_shipping')

    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.drop_column('cash_payment_only')
        batch_op.drop_column('platform_payment_only')
        batch_op.drop_column('pickup_only')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('allow_shipping')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('cash_payment_only')
        batch_op.drop_column('platform_payment_only')
        batch_op.drop_column('pickup_only')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('allow_shipping')

    # ### end Alembic commands ###
