"""Add verdieping and letter to Rek

Revision ID: ead4737031de
Revises: d1b687575aa8
Create Date: 2025-09-04 09:58:13.263722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead4737031de'
down_revision = 'd1b687575aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rek', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verdieping', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('letter', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rek', schema=None) as batch_op:
        batch_op.drop_column('letter')
        batch_op.drop_column('verdieping')

    # ### end Alembic commands ###
