"""beschrijving van wijziging

Revision ID: fbaadf605adb
Revises: 0b11b56bcbeb
Create Date: 2025-08-14 09:15:41.293261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaadf605adb'
down_revision = '0b11b56bcbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('pickup_only')
        batch_op.drop_column('platform_payment_only')
        batch_op.drop_column('allow_shipping')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('cash_payment_only')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.drop_column('pickup_only')
        batch_op.drop_column('platform_payment_only')
        batch_op.drop_column('allow_shipping')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('cash_payment_only')

    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_poster_buyer_id'), type_='foreignkey')
        batch_op.drop_column('pickup_only')
        batch_op.drop_column('buyer_id')
        batch_op.drop_column('platform_payment_only')
        batch_op.drop_column('allow_shipping')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('cash_payment_only')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_payment_only', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.NUMERIC(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('allow_shipping', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('platform_payment_only', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('buyer_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pickup_only', sa.BOOLEAN(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_poster_buyer_id'), 'user', ['buyer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('postcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_payment_only', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.NUMERIC(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('allow_shipping', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('platform_payment_only', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('pickup_only', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_payment_only', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.NUMERIC(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('allow_shipping', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('platform_payment_only', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('pickup_only', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
